trigger:
- main

pool: Agentpool_infra

jobs:
- job: infracodejob  
  displayName: infra-code-job
  pool: Agentpool_infra
  steps: 
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'pipeline service connection'
      backendAzureRmStorageAccountName: 'pipelinestorage1007'
      backendAzureRmContainerName: 'pipelinecontainer'
      backendAzureRmKey: 'terraform.tfstate'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'pipeline service connection'
- job: manualValidation
  displayName: MnualValidation
  dependsOn: infracodejob
  pool: server
  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 60  # approval ka wait time
    inputs:
      instructions: 'Please validate the infrastructure changes before proceeding.'
      onTimeout: 'reject' 
  